require("__tycoon__/prototypes/items/apple")
require("__tycoon__/prototypes/recipes/growing")
require("__tycoon__/prototypes/entities/apple-farm")
require("__tycoon__/prototypes/entities/houses")
require("__tycoon__/prototypes/entities/town-hall")
require("__tycoon__/prototypes/entities/water-tank")