data:extend{
    {
        type = "recipe",
        name = "tycoon-bicyle",
        category = "crafting",
        energy_required = 5,
        enabled = false,
        ingredients = {
            { type = "item", name = "iron-stick", amount = 10 },
            { type = "item", name = "tycoon-iron-chain", amount = 1 },
            { type = "item", name = "tycoon-tire", amount = 2 },
        },
        result = "tycoon-bicycle",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-iron-chain",
        category = "crafting",
        energy_required = 1,
        enabled = false,
        ingredients = {
            { type = "item", name = "iron-plate", amount = 5 },
        },
        result = "tycoon-iron-chain",
        result_count = 2,
    },
    {
        type = "recipe",
        name = "tycoon-candle",
        category = "chemistry",
        energy_required = 5,
        enabled = false,
        ingredients = {
            { type = "fluid", name = "petroleum", amount = 20 },
        },
        result = "tycoon-candle",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-cutlery",
        category = "crafting",
        energy_required = 10,
        enabled = false,
        ingredients = {
            { type = "item", name = "steel-plate", amount = 3 },
        },
        result = "tycoon-cutlery",
        result_count = 10,
    },
    {
        type = "recipe",
        name = "tycoon-laptop",
        category = "crafting",
        energy_required = 15,
        enabled = false,
        ingredients = {
            { type = "item", name = "plastic", amount = 3 },
            { type = "item", name = "steel-plate", amount = 1 },
            { type = "item", name = "advanced-circuit", amount = 20 },
            { type = "item", name = "processing-unit", amount = 4 },
            { type = "item", name = "tycoon-keyboard", amount = 1 },
            { type = "item", name = "copper-wire", amount = 10 },
        },
        result = "tycoon-laptop",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-keyboard",
        category = "crafting",
        energy_required = 1,
        enabled = false,
        ingredients = {
            { type = "item", name = "plastic", amount = 1 },
        },
        result = "tycoon-keyboard",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-smartphone",
        category = "crafting",
        energy_required = 10,
        enabled = false,
        ingredients = {
            { type = "item", name = "plastic", amount = 2 },
            { type = "item", name = "iron-plate", amount = 1 },
            { type = "item", name = "advanced-circuit", amount = 5 },
            { type = "item", name = "processing-unit", amount = 1 },
            { type = "item", name = "copper-wire", amount = 10 },
        },
        result = "tycoon-smartphone",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-television",
        category = "crafting",
        energy_required = 10,
        enabled = false,
        ingredients = {
            { type = "item", name = "plastic", amount = 4 },
            { type = "item", name = "advanced-circuit", amount = 2 },
            { type = "item", name = "copper-wire", amount = 10 },
        },
        result = "tycoon-television",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-pan",
        category = "crafting",
        energy_required = 2,
        enabled = false,
        ingredients = {
            { type = "item", name = "steel-plate", amount = 1 },
            { type = "item", name = "iron-stick", amount = 1 },
        },
        result = "tycoon-pan",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-pot",
        category = "crafting",
        energy_required = 2,
        enabled = false,
        ingredients = {
            { type = "item", name = "steel-plate", amount = 1 },
            { type = "item", name = "iron-stick", amount = 1 },
        },
        result = "tycoon-pot",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-soap",
        category = "chemistry",
        energy_required = 5,
        enabled = false,
        ingredients = {
            { type = "fluid", name = "light-oil", amount = 10 },
            { type = "item", name = "coal", amount = 2 },
        },
        result = "tycoon-soap",
        result_count = 5,
    },
    {
        type = "recipe",
        name = "tycoon-tire",
        category = "crafting",
        energy_required = 5,
        enabled = false,
        ingredients = {
            { type = "fluid", name = "plastic", amount = 2 },
        },
        result = "tycoon-tire",
        result_count = 5,
    },
}