data:extend{
    {
        type = "recipe",
        name = "tycoon-bicycle",
        category = "crafting",
        energy_required = 20,
        enabled = false,
        ingredients = {
            { type = "item", name = "iron-stick", amount = 10 },
            { type = "item", name = "tycoon-iron-chain", amount = 1 },
            { type = "item", name = "tycoon-tire", amount = 2 },
        },
        results = { { type = "item", name = "tycoon-bicycle", amount = 1 } },
        localised_name = { "item-name.tycoon-bicycle" },
    },
    {
        type = "recipe",
        name = "tycoon-iron-chain",
        category = "crafting",
        energy_required = 1,
        enabled = false,
        ingredients = {
            { type = "item", name = "iron-plate", amount = 5 },
        },
        results = { { type = "item", name = "tycoon-iron-chain", amount = 2 } },
        localised_name = { "item-name.tycoon-iron-chain" },
    },
    {
        type = "recipe",
        name = "tycoon-candle",
        category = "chemistry",
        energy_required = 3,
        enabled = false,
        ingredients = {
            { type = "fluid", name = "petroleum-gas", amount = 40 },
        },
        results = { { type = "item", name = "tycoon-candle", amount = 2 } },
        localised_name = { "item-name.tycoon-candle" },
    },
    {
        type = "recipe",
        name = "tycoon-gloves",
        category = "chemistry",
        energy_required = 1,
        enabled = false,
        ingredients = {
            { type = "fluid", name = "petroleum-gas", amount = 10 },
        },
        results = { { type = "item", name = "tycoon-gloves", amount = 2 } },
        localised_name = { "item-name.tycoon-gloves" },
    },
    {
        type = "recipe",
        name = "tycoon-cutlery",
        category = "crafting",
        energy_required = 10,
        enabled = false,
        ingredients = {
            { type = "item", name = "steel-plate", amount = 3 },
            { type = "item", name = "copper-plate", amount = 1 },
        },
        results = { { type = "item", name = "tycoon-cutlery", amount = 10 } },
        localised_name = { "item-name.tycoon-cutlery" },
    },
    {
        type = "recipe",
        name = "tycoon-laptop",
        category = "crafting",
        energy_required = 15,
        enabled = false,
        ingredients = {
            { type = "item", name = "plastic-bar", amount = 3 },
            { type = "item", name = "steel-plate", amount = 1 },
            { type = "item", name = "advanced-circuit", amount = 20 },
            { type = "item", name = "processing-unit", amount = 4 },
            { type = "item", name = "tycoon-keyboard", amount = 1 },
            { type = "item", name = "copper-cable", amount = 10 },
        },
        results = { { type = "item", name = "tycoon-laptop", amount = 1 } },
        localised_name = { "item-name.tycoon-laptop" },
    },
    {
        type = "recipe",
        name = "tycoon-keyboard",
        category = "crafting",
        energy_required = 1,
        enabled = false,
        ingredients = {
            { type = "item", name = "plastic-bar", amount = 1 },
            { type = "item", name = "electronic-circuit", amount = 1 },
        },
        results = { { type = "item", name = "tycoon-keyboard", amount = 1 } },
        localised_name = { "item-name.tycoon-keyboard" },
    },
    {
        type = "recipe",
        name = "tycoon-smartphone",
        category = "crafting",
        energy_required = 10,
        enabled = false,
        ingredients = {
            { type = "item", name = "plastic-bar", amount = 2 },
            { type = "item", name = "iron-plate", amount = 1 },
            { type = "item", name = "advanced-circuit", amount = 5 },
            { type = "item", name = "processing-unit", amount = 1 },
            { type = "item", name = "copper-cable", amount = 10 },
        },
        results = { { type = "item", name = "tycoon-smartphone", amount = 1 } },
        localised_name = { "item-name.tycoon-smartphone" },
    },
    {
        type = "recipe",
        name = "tycoon-television",
        category = "crafting",
        energy_required = 10,
        enabled = false,
        ingredients = {
            { type = "item", name = "plastic-bar", amount = 4 },
            { type = "item", name = "advanced-circuit", amount = 2 },
            { type = "item", name = "copper-cable", amount = 10 },
        },
        results = { { type = "item", name = "tycoon-television", amount = 1 } },
        localised_name = { "item-name.tycoon-television" },
    },
    {
        type = "recipe",
        name = "tycoon-cooking-pan",
        category = "crafting",
        energy_required = 1,
        enabled = false,
        ingredients = {
            { type = "item", name = "steel-plate", amount = 1 },
            { type = "item", name = "iron-stick", amount = 1 },
            { type = "item", name = "copper-plate", amount = 1 },
        },
        results = { { type = "item", name = "tycoon-cooking-pan", amount = 1 } },
        localised_name = { "item-name.tycoon-cooking-pan" },
    },
    {
        type = "recipe",
        name = "tycoon-cooking-pot",
        category = "crafting",
        energy_required = 1,
        enabled = false,
        ingredients = {
            { type = "item", name = "steel-plate", amount = 1 },
            { type = "item", name = "iron-stick", amount = 1 },
        },
        results = { { type = "item", name = "tycoon-cooking-pot", amount = 1 } },
        localised_name = { "item-name.tycoon-cooking-pot" },
    },
    {
        type = "recipe",
        name = "tycoon-soap",
        category = "chemistry",
        energy_required = 5,
        enabled = false,
        ingredients = {
            { type = "fluid", name = "light-oil", amount = 20 },
            { type = "item", name = "coal", amount = 5 },
        },
        results = { { type = "item", name = "tycoon-soap", amount = 5 } },
        localised_name = { "item-name.tycoon-soap" },
    },
    {
        type = "recipe",
        name = "tycoon-tire",
        category = "crafting",
        energy_required = 5,
        enabled = false,
        ingredients = {
            { type = "item", name = "plastic-bar", amount = 2 },
        },
        results = { { type = "item", name = "tycoon-tire", amount = 5 } },
        localised_name = { "item-name.tycoon-tire" },
    },
}
