data:extend{
    {
        type = "recipe",
        name = "tycoon-wheat-to-grain",
        category = "crafting",
        energy_required = 15,
        enabled = false,
        ingredients = {
            { type = "item", name = "tycoon-wheat", amount = 25 },
        },
        result = "tycoon-grain",
        result_count = 100,
    },
    {
        type = "recipe",
        name = "tycoon-flour-to-dough",
        category = "crafting-with-fluid",
        energy_required = 15,
        enabled = false,
        ingredients = {
            { type = "item", name = "tycoon-flour", amount = 30 },
            { type = "fluid", name = "tycoon-milk", amount = 20 },
        },
        result = "tycoon-dough",
        result_count = 20,
    },
    {
        type = "recipe",
        name = "tycoon-dough-to-bread",
        category = "smelting",
        energy_required = 1,
        enabled = false,
        ingredients = {
            { type = "item", name = "tycoon-dough", amount = 1 },
        },
        result = "tycoon-bread",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-grain-to-flour",
        category = "crafting",
        energy_required = 30,
        enabled = false,
        ingredients = {
            { type = "item", name = "tycoon-grain", amount = 5 },
        },
        result = "tycoon-flour",
        result_count = 50,
    },
    {
        type = "recipe",
        name = "tycoon-iron-plate-to-bottle",
        category = "crafting",
        energy_required = 30,
        enabled = false,
        ingredients = {
            { type = "item", name = "iron-plate", amount = 5 },
        },
        result = "tycoon-bottle",
        result_count = 50,
    },
    {
        type = "recipe",
        name = "tycoon-bottle-to-milk-bottle",
        category = "crafting-with-fluid",
        energy_required = 15,
        enabled = false,
        ingredients = {
            { type = "item", name = "tycoon-bottle", amount = 25 },
            { type = "fluid", name = "tycoon-milk", amount = 25 },
        },
        result = "tycoon-milk-bottle",
        result_count = 25,
    },
    {
        type = "recipe",
        name = "tycoon-refurbish-bottle",
        category = "crafting-with-fluid",
        subgroup = "tycoon-intermediate-products",
        order = "a[tycoon]-g[used-bottle]",
        energy_required = 15,
        enabled = false,
        icon = "__tycoon__/graphics/icons/used-bottle.png",
        icon_size = 64,
        ingredients = {
            { type = "item", name = "tycoon-used-bottle", amount = 25 },
            { type = "fluid", name = "water", amount = 100 },
        },
        results = {
            {name = "tycoon-bottle", amount = 20},
            {name = "tycoon-bottle", amount = 5, probability = 0.2}
        },
    },
    {
        type = "recipe",
        name = "tycoon-smoothie",
        category = "crafting-with-fluid",
        energy_required = 15,
        enabled = true,
        ingredients = {
            { type = "item", name = "tycoon-bottle", amount = 25 },
            { type = "item", name = "tycoon-apple", amount = 50 },
            { type = "fluid", name = "tycoon-milk", amount = 25 },
        },
        result = "tycoon-smoothie",
        result_count = 25,
    },
    {
        type = "recipe",
        name = "tycoon-apple-cake",
        category = "crafting",
        energy_required = 30,
        enabled = true,
        ingredients = {
            { type = "item", name = "tycoon-butter", amount = 2 },
            { type = "item", name = "tycoon-apple", amount = 5 },
            { type = "item", name = "tycoon-egg", amount = 2 },
            { type = "item", name = "tycoon-dough", amount = 1 },
        },
        result = "tycoon-apple-cake",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-butter",
        category = "crafting-with-fluid",
        energy_required = 60,
        enabled = true,
        ingredients = {
            { type = "fluid", name = "tycoon-milk", amount = 100 },
        },
        result = "tycoon-butter",
        result_count = 25,
    },
    {
        type = "recipe",
        name = "tycoon-cheese",
        category = "crafting-with-fluid",
        energy_required = 60,
        enabled = true,
        ingredients = {
            { type = "fluid", name = "tycoon-milk", amount = 100 },
        },
        result = "tycoon-cheese",
        result_count = 50,
    },
    {
        type = "recipe",
        name = "tycoon-burger",
        category = "crafting",
        energy_required = 15,
        enabled = true,
        ingredients = {
            { type = "item", name = "tycoon-cheese", amount = 1 },
            { type = "item", name = "tycoon-patty", amount = 1 },
            { type = "item", name = "tycoon-bread", amount = 1 },
        },
        result = "tycoon-burger",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-patty",
        category = "crafting",
        energy_required = 10,
        enabled = true,
        ingredients = {
            { type = "item", name = "tycoon-meat", amount = 1 },
        },
        result = "tycoon-patty",
        result_count = 1,
    },
    {
        type = "recipe",
        name = "tycoon-dumpling",
        category = "crafting",
        energy_required = 15,
        enabled = true,
        ingredients = {
            { type = "item", name = "tycoon-dough", amount = 1 },
            { type = "item", name = "tycoon-fish-filet", amount = 1 },
        },
        result = "tycoon-dumpling",
        result_count = 1,
    },
}