data:extend({
   {
        type = "research-achievement",
        name = "tycoon-residential",
        order = "a[tycoon]-a",
        icons = {
            { icon = "__tycoon__/graphics/achievements/residential.png", icon_size = 128 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/normal.png", icon_size = 128 },
        },
        icon_size = 128,
        limited_to_one_game = false,
        technology = "tycoon-residential-housing",
    },
    {
        type = "research-achievement",
        name = "tycoon-highrise",
        order = "a[tycoon]-b",
        icons = {
            { icon = "__tycoon__/graphics/achievements/highrise.png", icon_size = 128 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/silver.png", icon_size = 128 },
        },
        icon_size = 128,
        limited_to_one_game = false,
        technology = "tycoon-highrise-housing",
    },
    {
        type = "research-achievement",
        name = "tycoon-expansion",
        order = "a[tycoon]-c",
        icons = {
            { icon = "__tycoon__/graphics/achievements/cities.png", icon_size = 128 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/gold.png", icon_size = 128 },
        },
        icon_size = 128,
        limited_to_one_game = false,
        technology = "tycoon-new-cities",
    },
    {
        type = "achievement",
        name = "tycoon-population-100",
        order = "a[tycoon]-e",
        icons = {
            { icon = "__tycoon__/graphics/achievements/population.png", icon_size = 128 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/normal.png", icon_size = 128 },
        },
        localised_name = {"achievement-name.tycoon-population", "100"},
        localised_description = {"achievement-description.tycoon-population", "100"},
        icon_size = 128,
        limited_to_one_game = false,
    },
    {
        type = "achievement",
        name = "tycoon-population-1000",
        order = "a[tycoon]-f",
        icons = {
            { icon = "__tycoon__/graphics/achievements/population.png", icon_size = 128 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/silver.png", icon_size = 128 },
        },
        localised_name = {"achievement-name.tycoon-population", "1000"},
        localised_description = {"achievement-description.tycoon-population", "1000"},
        icon_size = 128,
        limited_to_one_game = false,
    },
    {
        type = "achievement",
        name = "tycoon-population-10000",
        order = "a[tycoon]-g",
        icons = {
            { icon = "__tycoon__/graphics/achievements/population.png", icon_size = 128 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/gold.png", icon_size = 128 },
        },
        localised_name = {"achievement-name.tycoon-population", "10k"},
        localised_description = {"achievement-description.tycoon-population", "10k"},
        icon_size = 128,
        limited_to_one_game = false,
    },
    {
        type = "achievement",
        name = "tycoon-population-100000",
        order = "a[tycoon]-h",
        icons = {
            { icon = "__tycoon__/graphics/achievements/population.png", icon_size = 128 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/epic.png", icon_size = 128 },
        },
        localised_name = {"achievement-name.tycoon-population", "100k"},
        localised_description = {"achievement-description.tycoon-population", "100k"},
        icon_size = 128,
        limited_to_one_game = false,
    },
    {
        type = "achievement",
        name = "tycoon-passenger-transport-100",
        order = "a[tycoon]-i",
        icons = {
            { icon = "__tycoon__/graphics/achievements/public-transport.png", icon_size = 128 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/normal.png", icon_size = 128 },
        },
        localised_name = {"achievement-name.tycoon-passenger-transport", "100"},
        localised_description = {"achievement-description.tycoon-passenger-transport", "100"},
        icon_size = 128,
        limited_to_one_game = false,
    },
    {
        type = "achievement",
        name = "tycoon-passenger-transport-1000",
        order = "a[tycoon]-j",
        icons = {
            { icon = "__tycoon__/graphics/achievements/public-transport.png", icon_size = 128 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/silver.png", icon_size = 128 },
        },
        localised_name = {"achievement-name.tycoon-passenger-transport", "1000"},
        localised_description = {"achievement-description.tycoon-passenger-transport", "1000"},
        icon_size = 128,
        limited_to_one_game = false,
    },
    {
        type = "achievement",
        name = "tycoon-passenger-transport-10000",
        order = "a[tycoon]-k",
        icons = {
            { icon = "__tycoon__/graphics/achievements/public-transport.png", icon_size = 128 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/gold.png", icon_size = 128 },
        },
        localised_name = {"achievement-name.tycoon-passenger-transport", "10k"},
        localised_description = {"achievement-description.tycoon-passenger-transport", "10k"},
        icon_size = 128,
        limited_to_one_game = false,
    },
    {
        type = "achievement",
        name = "tycoon-passenger-transport-100000",
        order = "a[tycoon]-l",
        icons = {
            { icon = "__tycoon__/graphics/achievements/public-transport.png", icon_size = 128 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/epic.png", icon_size = 128 },
        },
        localised_name = {"achievement-name.tycoon-passenger-transport", "100k"},
        localised_description = {"achievement-description.tycoon-passenger-transport", "100k"},
        icon_size = 128,
        limited_to_one_game = false,
    },
})
