data:extend({
    {
        type = "produce-achievement",
        name = "tycoon-bakery",
        order = "a[tycoon]-a",
        icon = "__tycoon__/graphics/icons/bread.png",
        icon_size = 64,
        limited_to_one_game = false,
        item_product = "tycoon-bread",
        amount = 1000,
    },
    {
        type = "research-achievement",
        name = "tycoon-residential",
        order = "a[tycoon]-b",
        icons = {
            { icon = "__tycoon__/graphics/icons/highrise-housing.png", icon_size = 64 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/epic.png", icon_size = 128 },
          },
        icon_size = 64,
        limited_to_one_game = false,
        technology = "tycoon-residential-housing",
    },
    {
        type = "research-achievement",
        name = "tycoon-highrise",
        order = "a[tycoon]-b",
        icon = "__tycoon__/graphics/icons/highrise-housing.png",
        icon_size = 64,
        limited_to_one_game = false,
        technology = "tycoon-highrise-housing",
    },
    {
        type = "research-achievement",
        name = "tycoon-expansion",
        order = "a[tycoon]-c",
        icon = "__tycoon__/graphics/icons/multiple-cities.png",
        icon_size = 64,
        limited_to_one_game = false,
        technology = "tycoon-new-cities",
    },
    {
        type = "build-entity-achievement",
        name = "tycoon-transportation-tycoon",
        order = "a[tycoon]-d",
        icons = {
            { icon = "__tycoon__/graphics/icons/passenger-train-station.png", icon_size = 64 },
            { icon = "__tycoon__/graphics/achievements/backgrounds/epic.png", icon_size = 128 },
          },
        icon_size = 128,
        limited_to_one_game = false,
        to_build = "tycoon-passenger-train-station",
        amount = 2
    },
    {
        type = "achievement",
        name = "tycoon-population-100",
        icon = "__tycoon__/graphics/icons/passengers/1.png",
        icon_size = 64,
        limited_to_one_game = false,
    },
    {
        type = "achievement",
        name = "tycoon-population-1000",
        icon = "__tycoon__/graphics/icons/passengers/2.png",
        icon_size = 64,
        limited_to_one_game = false,
    },
    {
        type = "achievement",
        name = "tycoon-population-10000",
        icon = "__tycoon__/graphics/icons/passengers/3.png",
        icon_size = 64,
        limited_to_one_game = false,
    },
    {
        type = "achievement",
        name = "tycoon-population-100000",
        icon = "__tycoon__/graphics/icons/passengers/4.png",
        icon_size = 64,
        limited_to_one_game = false,
    },
    {
        type = "achievement",
        name = "tycoon-population-1000000",
        icon = "__tycoon__/graphics/icons/passengers/5.png",
        icon_size = 64,
        limited_to_one_game = false,
    },
})
